name: scaffold
description: Scaffolding example.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.2.2
  collection: ^1.18.0
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.4.1
  flutter_bloc: ^9.1.0
  flutter_essentials_kit: ^2.5.0
  freezed_annotation: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pine: ^1.0.3
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  retrofit: ^4.1.0
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker: ^4.4.1
  rxdart: ^0.28.0
  http_mock_adapter: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  data_fixture_dart: ^2.2.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mockito: ^5.4.4
  mocktail: ^1.0.3
  retrofit_generator: ^9.1.2

flutter:
  generate: true
  uses-material-design: true
